feature-request:
  - '/\b(feature|feature request|enhancement|could you add|please add|roadmap)\b/i'
support:
  - '/\b(how do i|how to|help|setup|install|configuration|getting started|not working|error installing|troubleshoot)\b/i'
question:
  - '/\b(question|is it possible|can i|any way to)\b/i'
