support:
  - '/\b(how do I|how to|help|setup|install|configuration|not working|error installing|getting started|trouble with)\b/i'
feature-request:
  - '/\b(feature|feature request|would be great|could you add|please add|enhancement|roadmap)\b/i'
question:
  - '/\b(question|any way to|is it possible|can I)\b/i'
