# Security Policy

Please do not open public issues for potential security problems.

Email: security@buildermethods.com  
We’ll acknowledge within 72 hours and coordinate a fix and disclosure timeline.
