# Security Policy

Please do not open public issues for potential security problems.

Email: security@website.com  
We’ll acknowledge receipt within 72 hours and coordinate a fix and disclosure timeline.
