name: "🐛 Bug report"
description: Report a reproducible bug in Agent OS
title: "[Bug] <short description>"
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve Agent OS!
        **Issues are for reproducible bugs only.**
        • Feature ideas → Discussions (Ideas)
        • Questions/support → Discussions (Q&A) or Builder Methods Pro for guaranteed responses.

        👉 Ideas: https://github.com/buildermethods/agent-os/discussions/new?category=ideas
        👉 Q&A:   https://github.com/buildermethods/agent-os/discussions/new?category=q-a
        👉 Pro:   https://buildermethods.com/pro
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight checks
      options:
        - label: I searched existing issues and discussions for duplicates.
          required: true
        - label: I reproduced this on the latest Agent OS version.
          required: true
  - type: input
    id: version
    attributes:
      label: Agent OS version
      placeholder: e.g., v2.1.0 (or commit SHA)
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS, shell, IDE, model provider, etc.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce (from a clean state)
      placeholder: |
        1) …
        2) …
        3) …
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / errors
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs / screenshots (redact secrets)
      render: shell
  - type: markdown
    attributes:
      value: |
        **Want to fast-track a fix?**
        If you’re able, please open a PR that links to this issue after reproducing. We welcome bug-fix PRs.
