name: PR manual decline (label or button)

on:
  # One-click from the PR: add a "decline: ..." label
  pull_request_target:
    types: [labeled]

  # Optional manual button in the Actions tab
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to act on"
        required: true
      reason:
        description: "Canned reason"
        required: true
        type: choice
        options:
          - out-of-scope
          - needs-approved-link
          - low-info
          - duplicate
          - spam

permissions:
  pull-requests: write
  contents: read

jobs:
  decline:
    runs-on: ubuntu-latest

    steps:
      - name: Determine PR number and reason (from label or dispatch)
        id: vars
        uses: actions/github-script@v7
        with:
          script: |
            let prNumber, reason;
            if (context.eventName === "pull_request_target" && context.payload.action === "labeled") {
              prNumber = context.payload.pull_request.number;
              const label = context.payload.label.name || "";
              if (!label.startsWith("decline:")) {
                core.setOutput("skip", "true");
              } else {
                reason = label.replace(/^decline:\s*/i, "").trim().toLowerCase();
              }
            } else if (context.eventName === "workflow_dispatch") {
              prNumber = core.getInput("pr_number");
              reason = core.getInput("reason").toLowerCase();
            }

            core.setOutput("pr", prNumber || "");
            core.setOutput("reason", reason || "");
      - name: Stop if not a decline event
        if: steps.vars.outputs.skip == 'true' || steps.vars.outputs.pr == ''
        run: echo "No decline action to run."

      - name: Build canned message
        if: steps.vars.outputs.skip != 'true' && steps.vars.outputs.pr != ''
        id: msg
        uses: actions/github-script@v7
        with:
          script: |
            const reason = core.getInput("reason") || "${{ steps.vars.outputs.reason }}";
            let msg;
            switch (reason) {
              case "out-of-scope":
                msg = `Thanks for the PR! After reviewing the roadmap, this change isn’t a direction we plan to take in core.\n\nIf you publish this as a fork/plugin/example, please share it in **Discussions → Show & Tell** so others can use it.\n\nMarking as declined to keep the backlog focused.`;
                break;
              case "needs-approved-link":
                msg = `Thanks for the PR! For focus, we only review PRs that link to an **open \`bug\` Issue** or a **Discussion** labeled **\`approved\`**.\n\nPlease open a Discussion/Issue first and get maintainer approval. We’ll be happy to revisit once aligned.`;
                break;
              case "low-info":
                msg = `Thanks for the PR! We’re missing required details (Summary / Checklist / documented steps to test). Please update the PR with the full template and feel free to re-open.`;
                break;
              case "duplicate":
                msg = `Thanks for the PR! This appears to duplicate existing work/discussion. We’ll consolidate on the original thread and close this one to reduce churn.`;
                break;
              case "spam":
                msg = `Closing this PR. It doesn’t meet our contribution policy.`;
                break;
              default:
                msg = `Thanks for the PR! Closing per maintainer review.`;
            }
            core.setOutput("body", msg);

      - name: Comment, label, and close
        if: steps.vars.outputs.skip != 'true' && steps.vars.outputs.pr != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER="${{ steps.vars.outputs.pr }}"
          BODY="${{ steps.msg.outputs.body }}"

          # Comment as github-actions[bot]
          gh pr comment "$PR_NUMBER" \
            --repo "${{ github.repository }}" \
            --body "$BODY"

          # Add a 'declined' label (create it in repo settings first)
          gh pr edit "$PR_NUMBER" \
            --repo "${{ github.repository }}" \
            --add-label "declined"

          # Close the PR
          gh pr close "$PR_NUMBER" \
            --repo "${{ github.repository }}"
