name: Triage

on:
  issues:
    types: [opened, edited, labeled]

permissions:
  issues: write

jobs:
  label-and-route:
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels by regex
        uses: github/issue-labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/issue-labeler.yml

      - name: Close support issues with BM Pro pointer
        if: contains(join(fromJson(toJson(github.event.issue.labels)).*.name, ','), 'support')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "$(cat << 'MSG'
          Thanks for reaching out! We keep GitHub Issues for **reproducible bugs** only.

          • **Docs:** https://webste.com/thing
          • **Ideas & Q&A (public):** https://github.com/website/thing/discussions  
          • **Official support with guaranteed responses:** https://website.com/pro

          Closing this to keep the bug tracker focused. Hope the above helps!
          MSG
          )"
          gh issue close ${{ github.event.issue.number }}
